openapi: 3.1.0
info:
  title: Scientific GPT API
  version: 3.1.0
  description: >
    Кастомный API для научного ассистента GPT. Позволяет анализировать структуру и содержимое
    папки Universe на Google Drive, извлекать файлы и использовать их для машинного обучения и исследований.

servers:
  - url: https://scientific-api.vercel.app

paths:
  /drive/universe/analyze:
    post:
      operationId: analyzeUniverseFolder
      summary: Прочитать и проанализировать все текстовые и табличные файлы в папке Universe
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                max_depth:
                  type: integer
                  default: 5
      responses:
        '200':
          description: Содержимое файлов и краткая сводка
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        content:
                          type: string

  /graph/visualize:
    post:
      operationId: visualizeGraphData
      summary: Построить граф из узлов и рёбер
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nodes:
                  type: array
                  items:
                    type: string
                edges:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Граф в виде base64 изображения и Python-кода
          content:
            application/json:
              schema:
                type: object
                properties:
                  image_base64:
                    type: string
                  python_code:
                    type: string

x-openai:
  prompt-suggestions:
    - name: "🧠 Анализ данных в Universe"
      request: "Прочитай все текстовые файлы в папке Universe и сделай выводы"
      action: analyzeUniverseFolder
    - name: "📊 Построить граф по данным"
      request: "Построй граф из узлов и рёбер"
      action: visualizeGraphData
