openapi: 3.1.0
info:
  title: Scientific Assistant API
  version: 3.0.0
  description: >
    API-интерфейс кастомного GPT, обеспечивающий доступ к Google Drive,
    чтение, анализ и редактирование научных данных в формате CSV, JSON, PDF, IPYNB и др.

servers:
  - url: https://scientific-api.vercel.app

paths:
  /drive/universe/tree:
    get:
      operationId: getUniverseDriveTree
      summary: Получить актуальную структуру папки Universe
      parameters:
        - name: max_depth
          in: query
          required: false
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: Структура папки Universe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileNode'

  /drive/universe/tree/static:
    get:
      operationId: getCachedUniverseTree
      summary: Получить кешированную структуру папки Universe
      responses:
        '200':
          description: Статичная иерархия файлов и папок
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileNode'

  /drive/file:
    get:
      operationId: downloadDriveFile
      summary: Скачать содержимое файла по ID
      parameters:
        - name: file_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Содержимое файла
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string

  /drive/upload:
    post:
      operationId: uploadToDrive
      summary: Загрузить новый файл
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                mime_type:
                  type: string
                  default: text/plain
                content:
                  type: string
                parent_id:
                  type: string
      responses:
        '200':
          description: Информация о загруженном файле
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  mimeType:
                    type: string

  /drive/file/edit:
    post:
      operationId: editDriveFile
      summary: Изменить содержимое существующего файла
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id:
                  type: string
                new_content:
                  type: string
                mime_type:
                  type: string
                  default: text/plain
      responses:
        '200':
          description: Файл обновлён
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  file_id:
                    type: string

components:
  schemas:
    FileNode:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/FileNode'

x-openai:
  prompt-suggestions:
    - name: "📁 Быстрое дерево Universe"
      request: "Покажи структуру папки Universe"
      action: getCachedUniverseTree
    - name: "📖 Прочитать содержимое файла"
      request: "Считай содержимое файла с ID {file_id}"
      action: downloadDriveFile
    - name: "✍️ Редактировать файл"
      request: "Измени файл с ID {file_id}, добавив текст..."
      action: editDriveFile
    - name: "📤 Сохранить новый файл"
      request: "Создай новый файл с именем {имя} и содержимым..."
      action: uploadToDrive
