openapi: 3.1.0
info:
  title: Scientific Assistant API
  version: 2.1.0
  description: >
    API для кастомного GPT. Позволяет читать и анализировать научные статьи (arXiv, Semantic Scholar),
    загружать и визуализировать графы, работать с Google Drive и OpenML.

servers:
  - url: https://scientific-api.vercel.app

paths:

  /drive/upload:
    post:
      operationId: uploadToDrive
      summary: Загрузить файл в Google Drive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                mime_type:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Результат загрузки
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  mimeType:
                    type: string

  /drive/list:
    get:
      operationId: listDriveFiles
      summary: Получить список файлов из Google Drive
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: Список файлов
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        mimeType:
                          type: string
                        modifiedTime:
                          type: string

  /drive/file:
    get:
      operationId: downloadDriveFile
      summary: Скачать файл по ID из Google Drive
      parameters:
        - name: file_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Содержимое файла
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string

  /arxiv/fulltext:
    get:
      operationId: getArxivFullText
      summary: Получить статью с arXiv (включая PDF)
      parameters:
        - name: keywords
          in: query
          required: true
          schema:
            type: string
        - name: max_results
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Статья с arXiv
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  authors:
                    type: array
                    items:
                      type: string
                  abstract:
                    type: string
                  text:
                    type: string
                  source:
                    type: string

  /semantic/fulltext:
    get:
      operationId: getSemanticFullText
      summary: Получить статью из Semantic Scholar
      parameters:
        - name: keywords
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Статья из Semantic Scholar
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  abstract:
                    type: string
                  sections:
                    type: array
                    items:
                      type: object
                      properties:
                        heading:
                          type: string
                        content:
                          type: string

  /openml/data:
    get:
      operationId: getOpenMLData
      summary: Получить список датасетов или скачать CSV по did
      parameters:
        - name: tag
          in: query
          required: false
          schema:
            type: string
        - name: did
          in: query
          required: false
          schema:
            type: string
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [csv, json]
            default: json
      responses:
        '200':
          description: Результаты OpenML
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object

  /graph/visualize:
    post:
      operationId: visualizeGraph
      summary: Построить граф из узлов и связей
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nodes:
                  type: array
                  items:
                    type: string
                edges:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Изображение графа
          content:
            application/json:
              schema:
                type: object
                properties:
                  image_base64:
                    type: string
                  python_code:
                    type: string
