version: '3.8'

services:
  scientific-api:
    image: index.docker.io/gretk/scientific-api-app-image:scientific-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - COSMOS_DB_DATABASE=scientific-data
      - COSMOS_DB_ACCOUNT=scientific-api-server
      - SUBNET_NAME=subnet-nwivqmzl
      - VNET_NAME=vnet-euoxdfir
    volumes:
      - galaxy_data:/app/galaxy_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  galaxy_data: 